### PR TITLE
chore: bump `eth-ape` and plugins to 0.6.x

### LINKED ISSUE #41: Bump `eth-ape` to `0.6.x`
Also, related plugins `ape-vyper`, `ape-starknet` and `ape-cairo`.

### PR DESCRIPTION
**Pull request by cwkang1998**
Update `eth-ape` to latest version for dx as per title.

Fixes #41

### CODE REVIEW

**Comment by cwkang1998** [comment]
Breaking due to me using poetry 1.3.2, do we want to switch to that or do we want to keep using poetry 1.2 for now?

**Comment by tserg** [comment]
> CI breaking due to me using poetry 1.3.2, do we want to switch to that or do we want to keep using poetry 1.2 for now?

We can upgrade to 1.3.2

**Comment by cwkang1998** [comment]
Will update this PR after #43 goes in.

**Comment by cwkang1998** [comment]
If CI pass this should be good to go!

**Comment by tserg** [comment]
Thanks for taking this up!

**Pull request merged**
